In [2]:
import requests


#需要安裝外部套件 pip install requests
#requests可以使用下列HTTP六個方法，使用後會傳回一個Response物件
#六個方法裡，GET和POST是最常用的兩個方法，
#GET提交的參數會放在標頭中傳送(public)
#POST則是放在內容中傳送(private)
#GET: requests.get(url)向指定資源提交請求，可額外設定 params 參數字典。
#POSTT: requests.post(url)向指定資源提交請求，可額外設定 data 參數字典。
#PUTT: requests.put(url)向指定資源提供最新內容，可額外設定 data 參數字典。
#DELETET: requests.delete(url)請求刪除指定的資源。
#HEADT: requests.head(url)請求提供資源的回應標頭(不含內容)
#OPTIONST: requests.options(url)請求伺服器提供資源可用的功能選項



#一個csv的下載網址
url:str = "https://www.moeaea.gov.tw/ECW/populace/opendata/wHandOpenData_File.ashx?set_id=248"

#text1(url,params=None,**kwargs沒有限定數量的引數呼叫)
response:requests.Response = requests.get(url)

In [3]:
#檢查是否下載成功(status_code == 200)
if response.status_code==200:
    print("下載成功")
    s:str = response.text
    display(s)

    #擷取第一行
    row_data=s.split("\r\n")
    display(row_data)

    #寫入csv檔
    fileName="download"
    with open(fileName+".csv",mode="w",encoding="utf-8") as f1:
        f1.write(s)
    print("寫入csv檔成功")

elif response.status_code>=400:
    print("下載失敗")
elif response.status_code>200:
    print("下載有問題")

下載成功

'日期(年),單位,再生能源發電量合計,慣常水力,地熱,太陽光電,風力_小計,風力_陸域,風力_離岸,生質能_小計,生質能_固態,生質能_氣態,廢棄物\r\n2002,千度,5582829,2778901,0,348,15880,15880,0,410970,298373,112597,2376730\r\n2003,千度,6209739,3034516,0,461,23762,23762,0,394254,297092,97162,2756746\r\n2004,千度,6584988,3209869,0,584,25253,25253,0,348524,279081,69442,3000758\r\n2005,千度,7540945,4071374,0,960,91300,91300,0,323478,262376,61102,3053833\r\n2006,千度,7743848,4088351,0,1457,276075,276075,0,321292,266849,54443,3056674\r\n2007,千度,8324812,4417550,0,2180,439535,439535,0,302267,246865,55402,3163280\r\n2008,千度,8259060,4305105,0,4473,588265,588265,0,272489,226997,45491,3088727\r\n2009,千度,7809525,3748288,0,9113,786635,786635,0,229350,187521,41829,3036139\r\n2010,千度,8639758,4194101,0,21727,1026338,1026338,0,270038,234679,35359,3127554\r\n2011,千度,8987061,3999726,0,61623,1492677,1492677,0,236091,209739,26352,3196944\r\n2012,千度,10662097,5669558,0,159870,1413468,1413468,0,241460,218577,22883,3177741\r\n2013,千度,10855227,5422890,0,321096,1640008,1640008,0,225561,205350,20211,3245672\r\n2014,千度,9922382,4317862,0,528762,1500484,1500484,0,249783,231913,17870,3325490\r\n2015,千度,10476045,4470146,0,850268,1525236,1525236,0,246203,227420,18783,3384192\r\n2016,千度,12730120,6562041,0,1109005,1457102,1457102,0,205421,185762,19659,3396552\r\n2017,千度,12365425,5446815,0,1667453,1722459,1702077,20381,187698,169450,18248,3341001\r\n2018,千度,12646608,4481584,1,2703658,1709487,1682777,26710,185280,166440,18840,3566597\r\n2019,千度,15258373,5544796,757,4015948,1892232,1715855,176377,169780,151434,18346,3634861\r\n2020,千度,15179072,3019152,1912,6074674,2308872,1792791,516081,204718,141366,63353,3569744\r\n2021,千度,17511713,3474663,9074,7970191,2257478,1701480,555998,195794,153172,42622,3604514\r\n2022,千度,23844899,5836503,25008,10676988,3543061,2082798,1460263,158212,118278,39933,3605128\r\n'

['日期(年),單位,再生能源發電量合計,慣常水力,地熱,太陽光電,風力_小計,風力_陸域,風力_離岸,生質能_小計,生質能_固態,生質能_氣態,廢棄物',
 '2002,千度,5582829,2778901,0,348,15880,15880,0,410970,298373,112597,2376730',
 '2003,千度,6209739,3034516,0,461,23762,23762,0,394254,297092,97162,2756746',
 '2004,千度,6584988,3209869,0,584,25253,25253,0,348524,279081,69442,3000758',
 '2005,千度,7540945,4071374,0,960,91300,91300,0,323478,262376,61102,3053833',
 '2006,千度,7743848,4088351,0,1457,276075,276075,0,321292,266849,54443,3056674',
 '2007,千度,8324812,4417550,0,2180,439535,439535,0,302267,246865,55402,3163280',
 '2008,千度,8259060,4305105,0,4473,588265,588265,0,272489,226997,45491,3088727',
 '2009,千度,7809525,3748288,0,9113,786635,786635,0,229350,187521,41829,3036139',
 '2010,千度,8639758,4194101,0,21727,1026338,1026338,0,270038,234679,35359,3127554',
 '2011,千度,8987061,3999726,0,61623,1492677,1492677,0,236091,209739,26352,3196944',
 '2012,千度,10662097,5669558,0,159870,1413468,1413468,0,241460,218577,22883,3177741',
 '2013,千度,10855227,5422890,0,321096,1640008,1640008,0,225561,205350,20211,3245672',
 '2014,千度,9922382,4317862,0,528762,1500484,1500484,0,249783,231913,17870,3325490',
 '2015,千度,10476045,4470146,0,850268,1525236,1525236,0,246203,227420,18783,3384192',
 '2016,千度,12730120,6562041,0,1109005,1457102,1457102,0,205421,185762,19659,3396552',
 '2017,千度,12365425,5446815,0,1667453,1722459,1702077,20381,187698,169450,18248,3341001',
 '2018,千度,12646608,4481584,1,2703658,1709487,1682777,26710,185280,166440,18840,3566597',
 '2019,千度,15258373,5544796,757,4015948,1892232,1715855,176377,169780,151434,18346,3634861',
 '2020,千度,15179072,3019152,1912,6074674,2308872,1792791,516081,204718,141366,63353,3569744',
 '2021,千度,17511713,3474663,9074,7970191,2257478,1701480,555998,195794,153172,42622,3604514',
 '2022,千度,23844899,5836503,25008,10676988,3543061,2082798,1460263,158212,118278,39933,3605128',
 '']

寫入csv檔成功

In [4]:
import csv

#讀取csv檔成為python可以用的dict實體
with open(fileName+".csv",mode="r",encoding="utf-8") as f2:
    dict_reader=csv.DictReader(f2)
    csv_data:list[dict] = list(dict_reader)

    #尋找rowdata中某key中某值資料
    for item in csv_data:
        if item['日期(年)'] =='2022':
            print(item)

{'日期(年)': '2022', '單位': '千度', '再生能源發電量合計': '23844899', '慣常水力': '5836503', '地熱': '25008', '太陽光電': '10676988', '風力_小計': '3543061', '風力_陸域': '2082798', '風力_離岸': '1460263', '生質能_小計': '158212', '生質能_固態': '118278', '生質能_氣態': '39933', '廢棄物': '3605128'}

In [25]:
import pandas as pd
import lxml

#DataFrame是二維的包含欄位名稱和資料數列(0~n)
#用list[dict]生成DataFrame實體
df1 = pd.DataFrame(csv_data)
display("df1:")
display(df1)

#指定欄位
df2 = pd.DataFrame(csv_data,columns=["日期(年)","單位","再生能源發電量合計"])
display("df2:")
display(df2)

#用pandas.read_csv直接生成DataFrame實體
df3=pd.read_csv(fileName+".csv")
#只要某些欄位資料: DataFrame[[欄位1,欄位2,欄位3]]
columns=["日期(年)","單位","再生能源發電量合計"]
display("df3:")
display(df3[columns])


#用csv的string(爬蟲回來的string)產生DataFrame實體
from io import StringIO

strIO =StringIO(s)
df4=pd.read_csv(strIO)

display("df4:")
display(df4)

'df1:'

,日期(年),單位,再生能源發電量合計,慣常水力,地熱,太陽光電,風力_小計,風力_陸域,風力_離岸,生質能_小計,生質能_固態,生質能_氣態,廢棄物
0,2002,千度,5582829,2778901,0,348,15880,15880,0,410970,298373,112597,2376730
1,2003,千度,6209739,3034516,0,461,23762,23762,0,394254,297092,97162,2756746
2,2004,千度,6584988,3209869,0,584,25253,25253,0,348524,279081,69442,3000758
3,2005,千度,7540945,4071374,0,960,91300,91300,0,323478,262376,61102,3053833
4,2006,千度,7743848,4088351,0,1457,276075,276075,0,321292,266849,54443,3056674
5,2007,千度,8324812,4417550,0,2180,439535,439535,0,302267,246865,55402,3163280
6,2008,千度,8259060,4305105,0,4473,588265,588265,0,272489,226997,45491,3088727
7,2009,千度,7809525,3748288,0,9113,786635,786635,0,229350,187521,41829,3036139
8,2010,千度,8639758,4194101,0,21727,1026338,1026338,0,270038,234679,35359,3127554
9,2011,千度,8987061,3999726,0,61623,1492677,1492677,0,236091,209739,26352,3196944
10,2012,千度,10662097,5669558,0,159870,1413468,1413468,0,241460,218577,22883,3177741
11,2013,千度,10855227,5422890,0,321096,1640008,1640008,0,225561,205350,20211,3245672
12,2014,千度,9922382,4317862,0,528762,1500484,1500484,0,249783,231913,17870,3325490
13,2015,千度,10476045,4470146,0,850268,1525236,1525236,0,246203,227420,18783,3384192
14,2016,千度,12730120,6562041,0,1109005,1457102,1457102,0,205421,185762,19659,3396552
15,2017,千度,12365425,5446815,0,1667453,1722459,1702077,20381,187698,169450,18248,3341001
16,2018,千度,12646608,4481584,1,2703658,1709487,1682777,26710,185280,166440,18840,3566597
17,2019,千度,15258373,5544796,757,4015948,1892232,1715855,176377,169780,151434,18346,3634861
18,2020,千度,15179072,3019152,1912,6074674,2308872,1792791,516081,204718,141366,63353,3569744
19,2021,千度,17511713,3474663,9074,7970191,2257478,1701480,555998,195794,153172,42622,3604514
20,2022,千度,23844899,5836503,25008,10676988,3543061,2082798,1460263,158212,118278,39933,3605128

'df2:'

   日期(年)  單位 再生能源發電量合計
0   2002  千度   5582829
1   2003  千度   6209739
2   2004  千度   6584988
3   2005  千度   7540945
4   2006  千度   7743848
5   2007  千度   8324812
6   2008  千度   8259060
7   2009  千度   7809525
8   2010  千度   8639758
9   2011  千度   8987061
10  2012  千度  10662097
11  2013  千度  10855227
12  2014  千度   9922382
13  2015  千度  10476045
14  2016  千度  12730120
15  2017  千度  12365425
16  2018  千度  12646608
17  2019  千度  15258373
18  2020  千度  15179072
19  2021  千度  17511713
20  2022  千度  23844899

'df3:'

    日期(年)  單位  再生能源發電量合計
0    2002  千度    5582829
1    2003  千度    6209739
2    2004  千度    6584988
3    2005  千度    7540945
4    2006  千度    7743848
5    2007  千度    8324812
6    2008  千度    8259060
7    2009  千度    7809525
8    2010  千度    8639758
9    2011  千度    8987061
10   2012  千度   10662097
11   2013  千度   10855227
12   2014  千度    9922382
13   2015  千度   10476045
14   2016  千度   12730120
15   2017  千度   12365425
16   2018  千度   12646608
17   2019  千度   15258373
18   2020  千度   15179072
19   2021  千度   17511713
20   2022  千度   23844899

'df4:'

,日期(年),單位,再生能源發電量合計,慣常水力,地熱,太陽光電,風力_小計,風力_陸域,風力_離岸,生質能_小計,生質能_固態,生質能_氣態,廢棄物
0,2002,千度,5582829,2778901,0,348,15880,15880,0,410970,298373,112597,2376730
1,2003,千度,6209739,3034516,0,461,23762,23762,0,394254,297092,97162,2756746
2,2004,千度,6584988,3209869,0,584,25253,25253,0,348524,279081,69442,3000758
3,2005,千度,7540945,4071374,0,960,91300,91300,0,323478,262376,61102,3053833
4,2006,千度,7743848,4088351,0,1457,276075,276075,0,321292,266849,54443,3056674
5,2007,千度,8324812,4417550,0,2180,439535,439535,0,302267,246865,55402,3163280
6,2008,千度,8259060,4305105,0,4473,588265,588265,0,272489,226997,45491,3088727
7,2009,千度,7809525,3748288,0,9113,786635,786635,0,229350,187521,41829,3036139
8,2010,千度,8639758,4194101,0,21727,1026338,1026338,0,270038,234679,35359,3127554
9,2011,千度,8987061,3999726,0,61623,1492677,1492677,0,236091,209739,26352,3196944
10,2012,千度,10662097,5669558,0,159870,1413468,1413468,0,241460,218577,22883,3177741
11,2013,千度,10855227,5422890,0,321096,1640008,1640008,0,225561,205350,20211,3245672
12,2014,千度,9922382,4317862,0,528762,1500484,1500484,0,249783,231913,17870,3325490
13,2015,千度,10476045,4470146,0,850268,1525236,1525236,0,246203,227420,18783,3384192
14,2016,千度,12730120,6562041,0,1109005,1457102,1457102,0,205421,185762,19659,3396552
15,2017,千度,12365425,5446815,0,1667453,1722459,1702077,20381,187698,169450,18248,3341001
16,2018,千度,12646608,4481584,1,2703658,1709487,1682777,26710,185280,166440,18840,3566597
17,2019,千度,15258373,5544796,757,4015948,1892232,1715855,176377,169780,151434,18346,3634861
18,2020,千度,15179072,3019152,1912,6074674,2308872,1792791,516081,204718,141366,63353,3569744
19,2021,千度,17511713,3474663,9074,7970191,2257478,1701480,555998,195794,153172,42622,3604514
20,2022,千度,23844899,5836503,25008,10676988,3543061,2082798,1460263,158212,118278,39933,3605128